#
# Travis CI configuration file
#

dist: trusty
language: csharp

matrix:
  include:
    - os: linux
      dist: trusty # Ubuntu 14.04
      dotnet: 2.0.0
      mono: latest
      sudo: required
      env: MONO_BASE_PATH=/usr/lib/mono/
    - os: osx
      osx_image: xcode9 # macOS 10.12
      dotnet: 2.0.0
      mono: latest
      env: MONO_BASE_PATH=/Library/Frameworks/Mono.framework/Versions/Current/lib/mono/

addons:
  apt:
    packages:
      - dotnet-sharedframework-microsoft.netcore.app-1.0.5

env:
  global:
    - DOTNET_CLI_TELEMETRY_OPTOUT: 1
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true

install:
 - dotnet restore

solution: NGettext.sln

script:
  - dotnet restore
  - cd src/NGettext
  - FrameworkPathOverride=$MONO_BASE_PATH/2.0-api/ dotnet build --framework "net20"
  - FrameworkPathOverride=$MONO_BASE_PATH/4.0-api/ dotnet build --framework "net40"
  - FrameworkPathOverride=$MONO_BASE_PATH/4.5-api/ dotnet build --framework "net45"
  - TargetFrameworkRootPath=$MONO_BASE_PATH/xbuild-frameworks dotnet build --framework "portable-net40+sl5+win8+wp8"
  - TargetFrameworkRootPath=$MONO_BASE_PATH/xbuild-frameworks dotnet build --framework "portable-net40+sl5+win8+wpa81+wp8"
  - dotnet build --framework "netstandard1.0"
  - dotnet build --framework "netstandard1.3"
  - dotnet build --framework "netstandard2.0"
  - cd ../..
  - cd src/NGettext.PluralCompile
  - FrameworkPathOverride=$MONO_BASE_PATH/2.0-api/ dotnet build --framework "net20"
  - FrameworkPathOverride=$MONO_BASE_PATH/4.0-api/ dotnet build --framework "net40"
  - FrameworkPathOverride=$MONO_BASE_PATH/4.5-api/ dotnet build --framework "net45"
  - dotnet build --framework "netstandard1.3"
  - dotnet build --framework "netstandard2.0"
  - cd ../..
  - cd test/NGettext.Tests
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then dotnet test -f netcoreapp1.0; fi
  - dotnet test -f netcoreapp2.0
  - cd ../..
  - cd test/NGettext.PluralCompile.Tests
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then dotnet test -f netcoreapp1.0; fi
  - dotnet test -f netcoreapp2.0
